# ===================================================
# Fluent-Bit 서비스의 전역 행동 설정
# 수집 -> 전처리/추출 x -> 적제(배달) 컨셉
# logstach 연계(약간의 지연 발생)가 없었다면 여기서 전처리/필터링 등 작업이 수행될 수 있음
# ===================================================
[SERVICE]
    Flush       1       # 수집된 데이터를 몇 초 간격으로 내보낼 것인가(출력) 설정, 1초마다 데이터 전송 -> 실시간성 설정
    Log_Level   info    # Fluent-Bit 로그에 대한 레벨 설정 (erro, warn, info, debug), info : 일반 실행 정보, debug까지 출력

# ===================================================
# 데이터 수집 Input -> 어디서 데이터를 가져올 것인가
# input : sensor_json.log
# ===================================================
[INPUT]
    Name    tail                                      # 파일의 끝(tail)에서 읽어온다 -> 플러그인
    Path    /opt/airflow/sensor_logs/sensor_json.log  # 읽어올 로그 파일 경로 -> 날짜가 바뀌거나 파일이 커지면? 해결 필요
    Tag     sensor.json                               # 해당 데이터 tag 표시, 차후 output에서 태그를 보고 어디로 전송할지 필터링
    Parser  json                                      # 파일 내용을 미리 정의된 json 파서를 활용하여 구조화된 데이터로 인식 -> 후속 작업 x

# ===================================================
# input : sensor_text.log
# ===================================================
[INPUT]
    Name    tail
    Path    /opt/airflow/sensor_logs/sensor_text.log
    Tag     sensor.sensor_text

# ===================================================
# 데이터 배포 output -> 데이터를 어디로 보낼 것인가
# output : kafka
# ===================================================
[OUTPUT]
    # kafka 출력 플러그인 사용
    Name    kafka
    # tag가 sensor.json인 데이터만 출력 => 필터링
    Match   sensor.json
    # 전송할 곳 엔드포인트(kafka의 broker 주소)
    # (도커 컴포즈 상 서비스명) : 포트 => MSK의 엔드포인트로 교체
    Brokers kafka:9092
    # 데이터를 카프카로 보낼 때 -> 토픽명
    Topics  factory-json-Topic
    # 전송되는 데이터의 형식 -> json 형태 유지
    Format json

# ===================================================
# output : logstach(http 전송)
# ===================================================
[OUTPUT]