input {
    http {
        port => 5044
    }
}

filter {
    # 메세지에서 "ID=" 이 표현이 포함되는 경우만 파싱 진행 => 보험
    # grok : 비정형 텍스트를 구조화(반정형)된 데이터로 바꾸는 강력한 도구
    # [2026-04-24 10:38:52] ID=AI-FACTORY-001 |   TEMP:87.5 |   HUMI:42.1 |   STAT:RUNNING"
    # 정규표현식 패턴을 활용 => 키-값 으로 매핑
    # %{패턴명:필드명:데이터타입}
    if [message] =~ "ID=" {
        grok {
            match => { "message" => "\[%{TIMESTAMP_ISO8601:log_time}\] ID=%{DATA:device_id} \|   TEMP:%{NUMBER:temp:float} \|   HUMI:%{NUMBER:humi:float} \|   STAT:%{WORD:status}" }
        }
    }
}

output {
    kafka {
        bootstrap_servers => "kafka:9092"
        topic_id => "factory-text-topic"
        codec => json   
    }
    # 확인용 콘솔 출력 로그
    stdout {
        codec => rubydebug
    }
}