input {
    http {
        port => 5044
    }
}

filter {
    # 메세지에서 "ID=" 이 표현이 포함되는 경우만 파싱 진행 => 보험
    # grok : 비정형 텍스트를 구조화(반정형)된 데이터로 바꾸는 logstash가 가진 강력한 도구
    # 정규 표현식 패턴 활용 => 키-값 매핑
    # %{패턴명:필드명:데이터타입}
    if [message] =~ "ID=" {
        grok {

        }
    }
}
output {
    kafka {
        bootstrap-server => "kafka:9092"
        topic_id =>"factory-text-topic"
        codec => json
    }
    # 확인용 콘솔 출력 로그
    stdout {
        codec => rubydebug
    }
}